### PR TITLE
add, edit and delete tools

### PR DESCRIPTION
**Pull request by nataliack**

### CODE REVIEW

**Review by ablackwood777 — CHANGES_REQUESTED** [review]
There's an issue In src/Components/adminDashboard/Form/indexTwo.js 

On line 11 - you'll need to remove the MongoDB address which currently includes the exposed database password. You should be able to point to the config.env file which contains that full address instead.

Hope that's ok!

Thanks :)

**Review by ablackwood777 — CHANGES_REQUESTED** [review]
Hey Natalia :) From what I can see - it looks like you've just commented the line out (that contains the address/password) but not deleted it completely. That means it will still be viewable to anyone on Github. Just in case I've got that wrong - could you check again just to make sure? Thanks! :)

**Review by ablackwood777 — APPROVED** [review]
Cool - that looks good now! Thanks! :)

**Comment by nataliack** [comment]
Yeah, I saw that straight after - I committed another time - that time I
took out the password completely ;)

**Pull request merged**
